name: CI - Fine-Graind Assertions and Integration Tests with LocalStack

on:
  push:
    branches:
      - main

jobs:
  fine-grained-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run fine-grained tests
        run: npm run test:unit

  setup-localstack-environment:
    needs: fine-grained-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: 'latest'
          use-pro: 'true'
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Bootstrap LocalStack Environment
        run: npm run localstack:bootstrap
  
      - name: Save the Cloud Pod 
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          state-backend: cloud-pods
          state-name: bootstrapped-pod
          state-action: save
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

  integration-tests:
    needs: setup-localstack-environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Load the Cloud Pod 
        continue-on-error: false
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          state-backend: cloud-pods
          state-name: bootstrapped-pod
          state-action: load
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      
      - name: Deploy to LocalStack pod
        run: npm run localstack:deploy

      - name: Run integration tests
        run: npm run test:integration
      
      - name: Clean up stack
        run: npm run localstack:destroy